# Generated by Django 2.0.7 on 2018-07-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bookings", "0002_auto_20180703_1633")]

    operations = [
        migrations.AlterModelOptions(
            name="bookingrule", options={"ordering": ["order"]}
        ),
        migrations.AddField(
            model_name="bookingrule",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
