# Generated by Django 2.0.7 on 2018-07-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bookings", "0010_bookingtype_timezone")]

    operations = [
        migrations.CreateModel(
            name="BookingQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True, default=0)),
                ("question", models.CharField(max_length=255)),
                ("required", models.BooleanField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_questions",
                        to="bookings.BookingType",
                    ),
                ),
            ],
            options={"ordering": ["order"]},
        )
    ]
