# Generated by Django 2.0.7 on 2018-07-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_bookingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingquestion',
            name='question_type',
            field=models.CharField(choices=[('T', 'One Line'), ('M', 'Multi-line')], default='T', max_length=1),
            preserve_default=False,
        ),
    ]
