# Generated by Django 2.0.7 on 2018-07-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("bookings", "0014_config")]

    operations = [migrations.RemoveField(model_name="config", name="test")]
