# Generated by Django 2.0.7 on 2018-07-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bookings", "0015_remove_config_test")]

    operations = [
        migrations.AddField(
            model_name="config",
            name="google_credentials",
            field=models.TextField(default=""),
            preserve_default=False,
        )
    ]
