# Generated by Django 2.0.7 on 2018-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bookings", "0017_auto_20180709_1735")]

    operations = [
        migrations.AddField(
            model_name="bookingtype",
            name="icon",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
