# Generated by Django 3.0.1 on 2019-12-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_remove_bookingrule_recurring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mailchimp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
