# Generated by Django 3.0.4 on 2020-03-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_auto_20191220_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
