# Generated by Django 3.0.4 on 2020-06-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_booking_last_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtype',
            name='max_events_per_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtype',
            name='max_events_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
