# Generated by Django 3.0.4 on 2020-08-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_auto_20200623_1827'),
        ('bookings', '0024_bookingtype_hidden'),
    ]

    operations = [
    ]
