# Generated by Django 3.0.4 on 2020-08-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_merge_20200811_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
