# Generated by Django 3.1.5 on 2021-02-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_auto_20210217_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pending',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
