# Generated by Django 3.2 on 2022-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_auto_20210217_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtype',
            name='max_events_per_day_this_event',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max events per day (this event)'),
        ),
        migrations.AddField(
            model_name='bookingtype',
            name='max_events_per_month_this_event',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max events per month (this event)'),
        ),
        migrations.AddField(
            model_name='bookingtype',
            name='max_events_per_week_this_event',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max events per week (this event)'),
        ),
        migrations.AlterField(
            model_name='bookingtype',
            name='max_events_per_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max events per day (all events)'),
        ),
        migrations.AlterField(
            model_name='bookingtype',
            name='max_events_per_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max events per month (all events)'),
        ),
        migrations.AlterField(
            model_name='bookingtype',
            name='max_events_per_week',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max events per week (all events)'),
        ),
    ]
