# Generated by Django 4.2.3 on 2023-12-21 12:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0031_auto_20220615_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingtype",
            name="terms_message",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
