# Generated by Django 2.0.4 on 2018-05-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_site", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="client",
            field=models.CharField(max_length=255),
        )
    ]
