# Generated by Django 2.0.4 on 2018-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_site", "0003_testimonial_featured")]

    operations = [
        migrations.CreateModel(
            name="MainSliderImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
            ],
        )
    ]
