# Generated by Django 2.0.4 on 2018-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_site", "0004_mainsliderimage")]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instagram_url", models.URLField()),
            ],
            options={"abstract": False},
        )
    ]
