# Generated by Django 2.0.4 on 2018-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_site", "0009_auto_20180506_1813")]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        )
    ]
