# Generated by Django 2.0.4 on 2018-05-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_auto_20180506_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='mobile',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
