# Generated by Django 2.0.5 on 2018-05-07 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_auto_20180507_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsectionimage',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_site.AboutSection'),
        ),
    ]
