# Generated by Django 2.0.6 on 2018-07-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0025_auto_20180701_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='image_slider_speed',
            field=models.PositiveIntegerField(default=5000, verbose_name='Home page image slider speed (ms)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='testimonials_slider_speed',
            field=models.PositiveIntegerField(default=10000, verbose_name='Home page testimonials slider speed (ms)'),
        ),
    ]
