# Generated by Django 2.0.7 on 2018-07-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main_site", "0028_auto_20180701_1057")]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="related_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_site.Project",
            ),
        )
    ]
