# Generated by Django 2.0.7 on 2018-07-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0029_auto_20180709_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='related_project',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main_site.Project'),
        ),
    ]
