# Generated by Django 2.0.7 on 2018-07-15 10:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [("main_site", "0029_auto_20180709_1826")]

    operations = [
        migrations.CreateModel(
            name="DesignInsiderPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("content", tinymce.models.HTMLField()),
            ],
            options={"ordering": ["-date"], "get_latest_by": ["-date"]},
        ),
        migrations.RemoveField(model_name="siteconfig", name="calendly_url"),
    ]
