# Generated by Django 2.0.7 on 2018-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0030_auto_20180715_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='designinsiderpost',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
