# Generated by Django 2.0.7 on 2018-07-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0031_designinsiderpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='designinsiderpost',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
