# Generated by Django 2.0.7 on 2018-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0032_designinsiderpost_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designinsiderpost',
            name='content',
            field=models.TextField(),
        ),
    ]
