# Generated by Django 2.0.7 on 2018-08-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_site", "0035_auto_20180729_1005")]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="twitter_url",
            field=models.URLField(blank=True, default=""),
        )
    ]
