# Generated by Django 2.0.7 on 2018-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0037_auto_20180816_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='about_description',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='testimonials_description',
            field=models.TextField(blank=True),
        ),
    ]
