# Generated by Django 2.1.2 on 2018-12-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0044_siteconfig_homify_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='bark_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
