# Generated by Django 2.1.2 on 2019-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_site", "0046_newsletterentry")]

    operations = [
        migrations.AlterModelOptions(
            name="newsletterentry",
            options={"verbose_name_plural": "Newsletter entries"},
        ),
        migrations.AddField(
            model_name="newsletterentry",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
