# Generated by Django 2.1.2 on 2019-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0047_auto_20190127_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='designinsiderpost',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
