# Generated by Django 2.2.1 on 2019-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_site", "0050_auto_20190527_1409")]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="facebook_page_id",
            field=models.CharField(blank=True, default="", max_length=255),
        )
    ]
