# Generated by Django 2.1.3 on 2019-07-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0052_auto_20190703_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('T', 'Text'), ('I', 'Image')], default='T', max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('hover_image', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_site.Project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
