# Generated by Django 2.1.3 on 2019-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0053_projectitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='hover_image_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
