# Generated by Django 2.1.3 on 2019-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0055_remove_testimonial_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
