# Generated by Django 2.2.1 on 2019-07-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0057_auto_20190722_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='newsletter_group_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
