# Generated by Django 2.2.1 on 2019-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0058_siteconfig_newsletter_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterentry',
            name='email',
        ),
        migrations.AddField(
            model_name='newsletterentry',
            name='google_id',
            field=models.CharField(default='[none]', max_length=255),
            preserve_default=False,
        ),
    ]
