# Generated by Django 2.2.1 on 2019-08-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0059_auto_20190722_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='featured',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='featured_on',
            field=models.CharField(blank=True, choices=[('', '---'), ('H', 'Home page'), ('H', 'About page')], max_length=1, null=True),
        ),
    ]
