# Generated by Django 2.2.6 on 2019-10-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0060_auto_20191015_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_help_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Home how can I help background image'),
        ),
    ]
