# Generated by Django 2.2.1 on 2019-10-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0061_siteconfig_home_help_image'),
        ('main_site', '0060_auto_20190818_1726'),
    ]

    operations = [
    ]
