# Generated by Django 2.2.6 on 2019-11-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0062_auto_20191101_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='featured',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='featured_on',
            field=models.CharField(blank=True, choices=[('', '---'), ('H', 'Home page'), ('A', 'About page')], max_length=1, null=True),
        ),
    ]
