# Generated by Django 2.2.6 on 2019-11-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0063_auto_20191101_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='featured_on',
            field=models.CharField(blank=True, choices=[('', '---'), ('H', 'Home page'), ('A', 'About page'), ('S', 'About page'), ('C', 'About page')], max_length=1, null=True),
        ),
    ]
