# Generated by Django 2.2.6 on 2019-11-01 10:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0064_auto_20191101_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='about_mission_statement',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
