# Generated by Django 2.2.6 on 2019-11-01 10:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0065_auto_20191101_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='home_about_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
