# Generated by Django 2.2.6 on 2019-11-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0066_auto_20191101_1014'),
        ('main_site', '0062_merge_20191015_1723'),
    ]

    operations = [
    ]
