# Generated by Django 2.2.7 on 2019-11-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0067_auto_20191117_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='style',
            field=models.CharField(choices=[('L', 'Light'), ('D', 'Dark'), ('I', 'Image')], default='L', max_length=1),
            preserve_default=False,
        ),
    ]
