# Generated by Django 3.0.1 on 2019-12-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0069_auto_20191218_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletterentry',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='newsletterentry',
            name='google_id',
        ),
        migrations.AddField(
            model_name='newsletterentry',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletterentry',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletterentry',
            name='mailchimp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
