# Generated by Django 3.0.1 on 2019-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0070_auto_20191219_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='blog_header_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
