# Generated by Django 3.0.4 on 2020-03-23 11:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0071_siteconfig_blog_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineDesignStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='online_design_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='online_design_header_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='online_design_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='online_design_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='home_help_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Home how can I help text'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='featured_on',
            field=models.CharField(blank=True, choices=[('', '---'), ('H', 'Home page'), ('A', 'About page'), ('S', 'Services page'), ('C', 'Contact page'), ('O', 'Online design page')], max_length=1, null=True),
        ),
    ]
