# Generated by Django 3.0.4 on 2020-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0071_siteconfig_blog_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsliderimage',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
