# Generated by Django 3.0.4 on 2020-03-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0072_auto_20200323_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinedesignstep',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
