# Generated by Django 3.0.4 on 2020-04-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0074_auto_20200402_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinedesignstepbutton',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='main_site.OnlineDesignStep'),
        ),
        migrations.AlterField(
            model_name='servicebutton',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='main_site.Service'),
        ),
    ]
