# Generated by Django 3.0.4 on 2020-04-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0075_auto_20200402_1255'),
        ('main_site', '0072_mainsliderimage_url'),
    ]

    operations = [
    ]
