# Generated by Django 3.0.4 on 2020-04-22 12:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0077_auto_20200422_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='blog_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='online_design_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='portfolio_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='testimonials_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
