# Generated by Django 3.0.4 on 2020-08-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0078_auto_20200422_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='home_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_testimonials_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_testimonials_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_about_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_help_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_testimonials_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='services_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='services_testimonials_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
