# Generated by Django 3.1 on 2020-09-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0079_auto_20200811_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignInsiderPostRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_posts', to='main_site.designinsiderpost')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatee_posts', to='main_site.designinsiderpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
