# Generated by Django 3.1.3 on 2020-11-04 16:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0080_designinsiderpostrelated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='resources_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='resources_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='resources_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='resources_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
