# Generated by Django 3.1.5 on 2021-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0082_auto_20201204_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_form_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
