# Generated by Django 3.1.5 on 2021-02-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0084_siteconfig_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='apple_merchantid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
