# Generated by Django 3.1.5 on 2021-03-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0086_siteconfig_online_design_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='design_for_diversity_header_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='design_for_diversity_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='featured_on',
            field=models.CharField(blank=True, choices=[('', '---'), ('H', 'Home page'), ('A', 'About page'), ('S', 'Services page'), ('C', 'Contact page'), ('O', 'Online design page'), ('D', 'Design for Diversity page')], max_length=1, null=True),
        ),
    ]
