# Generated by Django 3.1.5 on 2021-03-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0087_auto_20210329_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='design_for_diversity_description',
            field=models.TextField(blank=True),
        ),
    ]
