# Generated by Django 3.1.5 on 2021-04-11 14:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0088_siteconfig_design_for_diversity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='designer_in_a_box_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='designer_in_a_box_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='designer_in_a_box_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
