# Generated by Django 3.1.5 on 2021-04-20 10:24

from django.db import migrations, models
import django.db.models.deletion
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0090_siteconfig_designer_in_a_box_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('draft', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('intro_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizStep',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('style', models.CharField(choices=[('rb', 'Multiple choice / radio button'), ('mb', 'Image moodboard'), ('ig', 'Image grid')], max_length=2)),
                ('question_text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizVariables',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[main_site.models.validate_variable_name])),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizStepAnswer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('effect', models.TextField(blank=True, null=True, validators=[main_site.models.validate_exec])),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.quizstep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('condition', models.TextField(blank=True, null=True, validators=[main_site.models.validate_eval])),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
