# Generated by Django 3.2 on 2021-04-20 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0092_auto_20210420_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSessionStepAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main_site.quizsession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.quizstep')),
            ],
        ),
    ]
