# Generated by Django 3.2 on 2021-04-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0093_quizsessionstepanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsessionstepanswer',
            name='step',
        ),
        migrations.AddField(
            model_name='quizsessionstepanswer',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_site.quizstepanswer'),
            preserve_default=False,
        ),
    ]
