# Generated by Django 3.2 on 2021-05-03 12:30

from django.db import migrations, models
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0094_auto_20210420_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizvariables',
            name='initial_vale',
            field=models.TextField(default=0, validators=[main_site.models.validate_eval]),
            preserve_default=False,
        ),
    ]
