# Generated by Django 3.2 on 2021-05-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0096_auto_20210503_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main_site.quiz'),
        ),
    ]
