# Generated by Django 3.2 on 2021-05-25 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0097_auto_20210503_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstepanswer',
            name='alt_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizstepanswer',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
