# Generated by Django 3.2 on 2021-05-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0098_auto_20210525_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstepanswer',
            name='alt_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
