# Generated by Django 3.2 on 2021-05-27 13:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0099_alter_quizstepanswer_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='quizstep',
            name='question_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
