# Generated by Django 3.2 on 2021-05-27 14:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0100_auto_20210527_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
