# Generated by Django 3.2 on 2021-05-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0101_alter_quizresult_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='result_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result_save_to_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
