# Generated by Django 3.2 on 2021-06-22 13:43

from django.db import migrations, models
import django.db.models.deletion
import main_site.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0102_auto_20210527_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gtin', models.CharField(max_length=255, validators=[main_site.models.validate_gtin], verbose_name='GTIN')),
                ('mpn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer part number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('availability', models.CharField(choices=[('https://schema.org/BackOrder', 'Back order')], max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_site.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('alt', models.TextField()),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_site.product')),
            ],
        ),
    ]
