# Generated by Django 3.2 on 2021-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0103_brand_product_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='product',
            name='draft',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('https://schema.org/BackOrder', 'Back order'), ('https://schema.org/Discontinued', 'Discontinued'), ('https://schema.org/InStock', 'In stock'), ('https://schema.org/InStoryOnly', 'In store only'), ('https://schema.org/LimitedAvailability', 'Limited availability'), ('https://schema.org/OnlineOnly', 'Online only'), ('https://schema.org/OutOfStock', 'Out of stock'), ('https://schema.org/PreOrdre', 'Pre order'), ('https://schema.org/PreSale', 'Pre sale'), ('https://schema.org/SoldOut', 'Sold out')], max_length=255),
        ),
    ]
