# Generated by Django 3.2 on 2021-06-23 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0108_alter_basketitem_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostageOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('public_name', models.CharField(max_length=255)),
                ('max_weight', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Max weight (kg)')),
                ('max_width', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Max width (cm)')),
                ('max_height', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Max height (cm)')),
                ('max_depth', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Max depth (cm)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('despatch_monday', models.BooleanField(blank=True)),
                ('despatch_tuesday', models.BooleanField(blank=True)),
                ('despatch_wednesday', models.BooleanField(blank=True)),
                ('despatch_thursday', models.BooleanField(blank=True)),
                ('despatch_friday', models.BooleanField(blank=True)),
                ('despatch_saturday', models.BooleanField(blank=True)),
                ('despatch_sunday', models.BooleanField(blank=True)),
                ('cutoff_time', models.TimeField()),
                ('transit_time_min', models.PositiveSmallIntegerField(verbose_name='Minimum transit time (days)')),
                ('transit_time_max', models.PositiveSmallIntegerField(verbose_name='Maximum transit time (days)')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Unit depth (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Unit height (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Unit weight (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Unit width (cm)'),
        ),
    ]
