# Generated by Django 3.2 on 2021-06-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0109_auto_20210623_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='postageoption',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=255),
        ),
        migrations.AlterField(
            model_name='postageoption',
            name='despatch_friday',
            field=models.BooleanField(blank=True, verbose_name='Despatch Friday'),
        ),
        migrations.AlterField(
            model_name='postageoption',
            name='despatch_monday',
            field=models.BooleanField(blank=True, verbose_name='Despatch Monday'),
        ),
        migrations.AlterField(
            model_name='postageoption',
            name='despatch_saturday',
            field=models.BooleanField(blank=True, verbose_name='Despatch Saturday'),
        ),
        migrations.AlterField(
            model_name='postageoption',
            name='despatch_sunday',
            field=models.BooleanField(blank=True, verbose_name='Despatch Sunday'),
        ),
        migrations.AlterField(
            model_name='postageoption',
            name='despatch_thursday',
            field=models.BooleanField(blank=True, verbose_name='Despatch Thursday'),
        ),
        migrations.AlterField(
            model_name='postageoption',
            name='despatch_tuesday',
            field=models.BooleanField(blank=True, verbose_name='Despatch Tuesday'),
        ),
        migrations.AlterField(
            model_name='postageoption',
            name='despatch_wednesday',
            field=models.BooleanField(blank=True, verbose_name='Despatch Wednesday'),
        ),
    ]
