# Generated by Django 3.2 on 2021-06-23 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0110_auto_20210623_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostageService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('public_name', models.CharField(max_length=255)),
                ('max_weight', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Max weight (kg)')),
                ('max_width', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Max width (cm)')),
                ('max_height', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Max height (cm)')),
                ('max_depth', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Max depth (cm)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('despatch_monday', models.BooleanField(blank=True, verbose_name='Despatch Monday')),
                ('despatch_tuesday', models.BooleanField(blank=True, verbose_name='Despatch Tuesday')),
                ('despatch_wednesday', models.BooleanField(blank=True, verbose_name='Despatch Wednesday')),
                ('despatch_thursday', models.BooleanField(blank=True, verbose_name='Despatch Thursday')),
                ('despatch_friday', models.BooleanField(blank=True, verbose_name='Despatch Friday')),
                ('despatch_saturday', models.BooleanField(blank=True, verbose_name='Despatch Saturday')),
                ('despatch_sunday', models.BooleanField(blank=True, verbose_name='Despatch Sunday')),
                ('cutoff_time', models.TimeField()),
                ('timezone', models.CharField(default='Europe/London', max_length=255)),
                ('handling_time_min', models.PositiveSmallIntegerField(verbose_name='Minimum handling time (days)')),
                ('handling_time_max', models.PositiveSmallIntegerField(verbose_name='Maximum handling time (days)')),
                ('transit_time_min', models.PositiveSmallIntegerField(verbose_name='Minimum transit time (days)')),
                ('transit_time_max', models.PositiveSmallIntegerField(verbose_name='Maximum transit time (days)')),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PostageServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='main_site.postageservice')),
            ],
        ),
        migrations.DeleteModel(
            name='PostageOption',
        ),
    ]
