# Generated by Django 3.2 on 2021-06-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0111_auto_20210623_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postageservicetype',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='postageservice',
            name='max_depth',
        ),
        migrations.RemoveField(
            model_name='postageservice',
            name='max_height',
        ),
        migrations.RemoveField(
            model_name='postageservice',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='postageservice',
            name='max_width',
        ),
        migrations.RemoveField(
            model_name='postageservice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='postageservice',
            name='public_name',
        ),
        migrations.AddField(
            model_name='postageservicetype',
            name='max_depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Max depth (cm)'),
        ),
        migrations.AddField(
            model_name='postageservicetype',
            name='max_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Max height (cm)'),
        ),
        migrations.AddField(
            model_name='postageservicetype',
            name='max_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Max weight (kg)'),
        ),
        migrations.AddField(
            model_name='postageservicetype',
            name='max_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Max width (cm)'),
        ),
        migrations.AddField(
            model_name='postageservicetype',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postageservicetype',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='postageservicetype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
