# Generated by Django 3.2 on 2021-06-23 13:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0112_auto_20210623_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='postageservice',
            name='country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
            preserve_default=False,
        ),
    ]
