# Generated by Django 3.2 on 2021-06-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0114_auto_20210623_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
