# Generated by Django 3.2 on 2021-07-09 12:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0116_auto_20210709_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
