# Generated by Django 3.2 on 2021-07-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0119_auto_20210709_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='state',
            field=models.CharField(choices=[('C', 'Creation'), ('P', 'Paid')], default='C', max_length=1),
        ),
    ]
