# Generated by Django 3.2 on 2021-07-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0121_auto_20210709_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
