# Generated by Django 3.2 on 2021-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0122_basket_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postageservice',
            name='rm_service_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Royal Mail service code'),
        ),
        migrations.AddField(
            model_name='postageservicetype',
            name='rm_package_format_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Royal Mail package format identifier'),
        ),
    ]
