# Generated by Django 3.2 on 2021-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0123_auto_20210718_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='rm_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Royal Mail order ID'),
        ),
    ]
