# Generated by Django 3.2 on 2021-08-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0127_auto_20210731_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='results_email_header_background',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='results_email_header_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='results_email_subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
