# Generated by Django 3.2 on 2021-08-03 15:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0129_siteconfig_shop_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='result_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='result_save_to_email',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
