# Generated by Django 3.2 on 2021-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0130_auto_20210803_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_ordered_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
