# Generated by Django 3.2 on 2021-08-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0131_product_back_ordered_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email_shop',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
