# Generated by Django 3.2 on 2021-08-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0134_auto_20210819_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='banner_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
