# Generated by Django 3.2 on 2021-08-22 18:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0135_siteconfig_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_submitted_texts',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
