# Generated by Django 3.2 on 2021-09-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0137_auto_20210913_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='draft',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
