# Generated by Django 3.2 on 2021-12-09 10:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0139_auto_20210927_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_form_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
