# Generated by Django 3.2 on 2022-01-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0140_siteconfig_contact_form_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_headshot_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
