# Generated by Django 3.2 on 2022-05-12 14:12

from django.db import migrations, models
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0141_siteconfig_about_headshot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[main_site.models.validate_gtin], verbose_name='GTIN'),
        ),
    ]
