# Generated by Django 4.1.3 on 2022-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0142_alter_product_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='blog_sidebar_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
