# Generated by Django 4.1.4 on 2022-12-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0144_contactformquestion_contactformquestionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_testimonials_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_top_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_top_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_about_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_help_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_testimonials_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='services_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='services_testimonials_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactformquestion',
            name='question_type',
            field=models.CharField(choices=[('T', 'One Line'), ('M', 'Multi-line'), ('S', 'Select'), ('U', 'Multi-select')], max_length=1),
        ),
    ]
