# Generated by Django 4.1.4 on 2023-01-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0145_siteconfig_about_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
