# Generated by Django 4.1.4 on 2023-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0146_siteconfig_about_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_cta_link',
            field=models.URLField(blank=True),
        ),
    ]
