# Generated by Django 4.2.3 on 2023-07-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0148_siteconfig_blod_header_siteconfig_contact_header_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='blod_header',
            new_name='blog_header',
        ),
    ]
