# Generated by Django 4.2.3 on 2023-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_site", "0149_rename_blod_header_siteconfig_blog_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="booking_cta",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
