# Generated by Django 4.2.3 on 2023-09-05 12:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_site", "0150_siteconfig_booking_cta"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", ckeditor_uploader.fields.RichTextUploadingField()),
                ("order", models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="servicesummary",
            options={"ordering": ["order"], "verbose_name_plural": "Service Summaries"},
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="faq_cta",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="faq_cta_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="faq_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="faq_header",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="faq_header_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="faq_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
