# Generated by Django 4.2.3 on 2023-09-05 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_site",
            "0151_faq_alter_servicesummary_options_siteconfig_faq_cta_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["order"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
    ]
