# Generated by Django 4.2.3 on 2023-10-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_site", "0153_siteconfig_resources_bio_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="noindex",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="noindex",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
