# Generated by Django 4.2.11 on 2024-04-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0154_category_noindex_product_noindex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteconfig",
            old_name="about_header",
            new_name="about_why_header",
        ),
        migrations.RenameField(
            model_name="siteconfig",
            old_name="about_image_2",
            new_name="about_why_header_image",
        ),
    ]
