# Generated by Django 4.2.11 on 2024-04-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0155_rename_about_header_siteconfig_about_why_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="about_header",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
