# Generated by Django 4.2.11 on 2024-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0156_siteconfig_about_header"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="siteconfig",
            name="testimonials_slider_speed",
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="home_slider_text",
            field=models.TextField(blank=True),
        ),
    ]
