# Generated by Django 4.2.11 on 2024-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0157_alter_quiz_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[("M", "Home page"), ("O", "Services page")],
                default="O",
                max_length=1,
            ),
        ),
    ]
