# Generated by Django 4.2.11 on 2024-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0158_alter_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="contact_cta_show",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
