# Generated by Django 5.0.7 on 2024-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0159_siteconfig_contact_cta_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
