# Generated by Django 5.1.1 on 2024-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0161_siteconfig_services_other_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='notification_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
