---
- name: Create folder
  file:
    path: /opt/apps/lmisite
    state: directory
  run_once: true  
    
- name: Create venv
  shell: "python3 -m venv /opt/apps/lmisite/env"
  run_once: true

- name: Copy files
  synchronize:
    src: lmisite/
    dest: /opt/apps/lmisite/src
    delete: true
    rsync_opts:
    - "--exclude=/db.sqlite3"
    - "--exclude=/media"
    - "--exclude=/static"
  run_once: true

- name: Set media permissions
  file:
    path: /opt/apps/lmisite/src/media
    owner: www-data
    group: www-data
    recurse: true
  
- name: Copy db password
  template:
    src: templates/db_pass.j2
    dest: /opt/apps/lmisite/src/db_pass
    owner: www-data
    group: www-data
    mode: 0640
  run_once: true

- name: Copy db name
  template:
    src: templates/db_name.j2
    dest: /opt/apps/lmisite/src/db_name
    owner: www-data
    group: www-data
    mode: 0640
  run_once: true
  
- name: Create db
  mysql_db:
    login_unix_socket: "/run/mysqld/mysqld.sock"
    name: lmisite
    encoding: utf8
    state: present
  
- name: Create db user
  mysql_user:
    login_unix_socket: "/run/mysqld/mysqld.sock"
    name: lmisite
    host: "%"
    state: present
    password: "{{ db_pass}}"
    priv: "lmisite.*:ALL"
  run_once: true
  
- name: Install dependencies
  pip:
    requirements: /opt/apps/lmisite/src/requirements.txt
    state: latest
    virtualenv: /opt/apps/lmisite/env
  run_once: true

- name: Migrate database
  command: "/opt/apps/lmisite/env/bin/python3 /opt/apps/lmisite/src/manage.py migrate"
  
- name: Collect static 
  command: "/opt/apps/lmisite/env/bin/python3 /opt/apps/lmisite/src/manage.py collectstatic --noinput"


- name: Create vassal config
  copy:
    src: files/lmisite.ini
    dest: /etc/uwsgi-emperor/vassals/lmisite.ini

- name: Create nginx config
  copy:
    src: files/nginx
    dest: /etc/nginx/sites-enabled/lmisite

- name: Issue certificates
  shell: "certbot -m {{ letsencrypt_email }} --agree-tos -d louisemisellinteriors.co.uk -d www.louisemisellinteriors.co.uk -d louisemisellinteriors.ltd.uk -d www.louisemisellinteriors.ltd.uk -d louisemisellinteriors.com -d www.louisemisellinteriors.com -n certonly --expand --webroot -w /var/www/html"
  args:
    creates: /etc/letsencrypt/live/louisemisellinteriors.co.uk

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
